# Generated by Django 3.0.6 on 2020-05-13 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_entrancesignal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntranceSignal',
        ),
    ]
